const mockedList = [
  {
    id: 1,
    description: 'Resma Papel A4',
    measurementUnit: 'cx',
    inStock: '4',
    purchasePrice: '10.00',
    salePrice: '25.00',
  },
  {
    id: 2,
    description: 'Camisa Branca P',
    measurementUnit: 'und',
    inStock: '16',
    purchasePrice: '10.00',
    salePrice: '0.00',
  },
  {
    id: 3,
    description: 'Resma Papel Sublimático',
    measurementUnit: 'und',
    inStock: '15',
    purchasePrice: '15.00',
    salePrice: '25.00',
  },
  {
    id: 4,
    description: 'Cola Branca',
    measurementUnit: 'und',
    inStock: '0',
    purchasePrice: '10.00',
    salePrice: '25.00',
  },
  {
    id: 5,
    description: 'Cola De Isopor',
    measurementUnit: 'und',
    inStock: '20',
    purchasePrice: '3.00',
    salePrice: '6.00',
  },
  {
    id: 6,
    description: 'Canecas (Cores Variadas)',
    measurementUnit: 'und',
    inStock: '15',
    purchasePrice: '15.00',
    salePrice: '35.00',
  },
  {
    id: 7,
    description: 'Copo Long Drink Degradê',
    measurementUnit: 'und',
    inStock: '17',
    purchasePrice: '4.00',
    salePrice: '7.00',
  },
  {
    id: 8,
    description: 'Camisa Branca G',
    measurementUnit: 'und',
    inStock: '13',
    purchasePrice: '15.00',
    salePrice: '35.00',
  },
  {
    id: 9,
    description: 'Camisa Branca M',
    measurementUnit: 'und',
    inStock: '0',
    purchasePrice: '20.00',
    salePrice: '0.00',
  },
  {
    id: 10,
    description: 'Resma Papel FotoAdesivo',
    measurementUnit: 'pct',
    inStock: '5',
    purchasePrice: '20.00',
    salePrice: '40.00',
  },
  {
    id: 11,
    description: 'Toner Kyocera BK',
    measurementUnit: 'und',
    inStock: '3',
    purchasePrice: '5.00',
    salePrice: '0.00',
  },
  {
    id: 12,
    description: 'Tinta Ciano Epson',
    measurementUnit: 'und',
    inStock: '2',
    purchasePrice: '5.00',
    salePrice: '0.00',
  },
  {
    id: 13,
    description: 'Tinta Magenta Epson',
    measurementUnit: 'und',
    inStock: '2',
    purchasePrice: '4.00',
    salePrice: '0.00',
  },
];


export default mockedList;